export const ROOM_SELECTED = "ROOM_SELECTED";
export const ROOM_TO_CONNECT = "ROOM_TO_CONNECT";
export const SET_MESSAGES = "SET_MESSAGES";
export const SET_MESSAGE = "SET_MESSAGE";

export const SET_MESSAGE_ARRAY = "SET_MESSAGE_ARRAY";
export const CREATE_NEW_USER = "CREATE_NEW_USER";

export const GET_USER_LOGED = "GET_USER_LOGED";

export const CLOSE_SESION = "CLOSE_SESION";

export const GET_SIGN_IN_USER = "GET_SIGN_IN_USER";
